apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: sender
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    selector:
      matchLabels:
        app: sender
